name: "tagged-release"

on:
  release:
    types: [prereleased]
  push:
    tags:
      - /.*/

jobs:
  build:
    # todo: run on both OS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test Types
      run: yarn test:types
    - name: Test
      run: yarn test

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        pre_release: ${{ github.event.release.prerelease }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}