name: "tagged-release"

on:
  release:
    types: [released, prereleased]
  push:
    tags:
      - /.*/

jobs:
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}